export const baseUrl = 'https://api.themoviedb.org/3'
export const API_KEY = '1c532ab5d251f9b05da92af60b829de0'
export const imageUrl = `https://image.tmdb.org/t/p/original`
export const trending = `${baseUrl}/trending/all/week?api_key=${API_KEY}&language=en-US`
export const action = `${baseUrl}/discover/movie?api_key=${API_KEY}&with_genres=28`
export const originals = `${baseUrl}/discover/tv?api_key=${API_KEY}&with_networks=213`
export const ComedyMovies = `${baseUrl}/discover/movie?api_key=${API_KEY}&with_genres=35`
export const HorrorMovies = `${baseUrl}/discover/movie?api_key=${API_KEY}&with_genres=27`
export const ActionMovies = `${baseUrl}/discover/movie?api_key=${API_KEY}&with_genres=28`
export const RomanceMovies = `${baseUrl}/discover/movie?api_key=${API_KEY}&with_genres=10749`
export const Documentaries = `${baseUrl}/discover/movie?api_key=${API_KEY}&with_genres=99`